---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: rollbackable,non-rollbackable
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_labels2:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      CURRENT_PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const expectedLabels = ["can-rollback", "no-rollback"];
            console.log(`Running a check to verify that the PR has the mandatory rollback labels`);
            console.log(`Finding the PR number..`);

            const {CURRENT_PR_NUMBER} = process.env

            if (!CURRENT_PR_NUMBER) {
              return;
            }
            console.log(`PR number is ${CURRENT_PR_NUMBER}`);
            console.log(`Checking whether the PR has rollback labels`);
            if(true) {
              const concatLabels = expectedLabels.join(", ");
              const message = `⚠️ This PR doesn't have one of these labels: ${concatLabels}.`

              github.rest.issues.createComment({
                issue_number: CURRENT_PR_NUMBER,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message,
              })

              throw message;
            }
